[phases.setup]
cmds = [
  "mkdir -p /root && touch /root/.profile"
]

[phases.install]
cmds = [
  "npm ci --prefix backend",
  "npm ci --prefix frontend"
]

[phases.build]
cmds = [
  "npm run build --prefix frontend"
]
shell = "/bin/sh"

[start]
cmd = "node backend/server.js"

[[ports]]
port = 5001
